### ISSUE TITLE
How to map the icon name to the library's enum? 

### ISSUE THREAD

**Issue by klwoon** [ranesr/SwiftIcons#10]
For example the IcoFont `5-start-hotel` is referenced by `.icofont(.fiveStarHotel)`, is there any direct mapping?

Or is there any way to reference the icon using unicode? such as `ef05` to get `5-star-hotel`.

![screen shot 2017-06-30 at 3 47 36 pm](https://user-images.githubusercontent.com/9354867/27726072-8bb083c6-5dab-11e7-9550-c28f5aec0991.png)

**Comment by ranesr** [comment]
@klwoon Unfortunately, there is no direct mapping. The only reason why there is no direct mapping for examples like `5-star-hotel` is because `Apple` does not allow to start case values for enum with an integer. Also, `Apple` does not allow keywords to be case values for enum.  All the other icons should be mapped to there icon name.

**Comment by klwoon** [comment]
Thanks for the reply, this library is great!
